# Generated by Django 2.2.19 on 2021-10-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20211006_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.TextField(max_length=40),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.TextField(max_length=100),
        ),
    ]
