# Generated by Django 2.2.19 on 2021-10-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20211007_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.TextField(blank=True, max_length=40, null=True),
        ),
    ]
